{
  "trial_number": 7,
  "timestamp": 1755957475.6090822,
  "error_type": "ValueError",
  "error_message": "CategoricalDistribution does not support dynamic value space.",
  "traceback": "Traceback (most recent call last):\n  File \"/Users/joseluna/master/Tesis/blstm_text/scripts/hyperopt.py\", line 883, in objective\n    config_dict, _ = create_trial_config(trial, hyperparams=HYPERPARAMS)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/joseluna/master/Tesis/blstm_text/scripts/hyperopt.py\", line 536, in create_trial_config\n    hidden_dim = trial.suggest_categorical('hidden_dim', hyperparams.HIDDEN_DIM)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.11/site-packages/optuna/trial/_trial.py\", line 404, in suggest_categorical\n    return self._suggest(name, CategoricalDistribution(choices=choices))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.11/site-packages/optuna/trial/_trial.py\", line 635, in _suggest\n    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)\n  File \"/opt/anaconda3/lib/python3.11/site-packages/optuna/storages/_cached_storage.py\", line 171, in set_trial_param\n    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)\n  File \"/opt/anaconda3/lib/python3.11/site-packages/optuna/storages/_rdb/storage.py\", line 568, in set_trial_param\n    self._set_trial_param_without_commit(\n  File \"/opt/anaconda3/lib/python3.11/site-packages/optuna/storages/_rdb/storage.py\", line 603, in _set_trial_param_without_commit\n    trial_param.check_and_add(session)\n  File \"/opt/anaconda3/lib/python3.11/site-packages/optuna/storages/_rdb/models.py\", line 360, in check_and_add\n    self._check_compatibility_with_previous_trial_param_distributions(session)\n  File \"/opt/anaconda3/lib/python3.11/site-packages/optuna/storages/_rdb/models.py\", line 376, in _check_compatibility_with_previous_trial_param_distributions\n    distributions.check_distribution_compatibility(\n  File \"/opt/anaconda3/lib/python3.11/site-packages/optuna/distributions.py\", line 670, in check_distribution_compatibility\n    raise ValueError(\nValueError: CategoricalDistribution does not support dynamic value space.\n",
  "training_time": 0.0035321712493896484,
  "training_time_minutes": 5.8869520823160805e-05,
  "parameters": {},
  "config": null
}